<?php


function lw_user_flow_menu() {
$items['user_delete_oldclass_data'] = array(
    'title' => 'Student Update Class Form',
     'page callback' => 'user_delete_oldclass_data',
   // 'page arguments' => array('user_delete_oldclass_data'),
    'access callback' => TRUE,
  );

  return $items;

}

function user_delete_oldclass_data(){
$school_name = 'MWS';//230911
$school_ID = 230908;
$class = '6';


$not_delete_student = array('21742','21729','21706','21724','21570','22033','22029','21987');
  $school_query = db_select('field_data_field_student_school_identifier', 'si');
  $school_query->join('profile','p','p.pid = si.entity_id');
  $school_query->join('field_revision_field_class_user','cu','cu.entity_id = p.pid');
  $school_query->join('taxonomy_term_data','ttd','ttd.tid = cu.field_class_user_tid');
  $school_query->fields('si',array('entity_id'));
  $school_query->fields('p',array('uid'));
  $school_query->fields('cu',array('field_class_user_tid'));
  $school_query->fields('ttd',array('tid','name'));
  $school_query->condition('si.field_student_school_identifier_nid',$school_ID);
  $school_query->condition('cu.delta',0);
  $school_query->condition('ttd.name',$class);
  $school_query->condition('p.uid',$not_delete_student,'NOT IN');
  $school_result = $school_query->execute()->fetchall(); 
  foreach ($school_result as $key => $value) {
       $profile_uid[] = $value->uid;
  }

echo '<pre>';
print_r($profile_uid);

//die();
foreach ($profile_uid as $key => $user_id) {
        //  $user_id = 21885;
          $fullUser = user_load($user_id);
          $updateUserParams = (array) $fullUser;
          $updateUserParams['field_excellone'][LANGUAGE_NONE][0]['value'] = 0;
          $as =  user_save($fullUser, $updateUserParams);
if($as){
      $output =  drupal_set_message('Data is Delete Susccess fully'.$user_id);
  }

}

drupal_set_message('Update all '.sizeof($profile_uid).' User');
return $output;
}
