<?php

/**
 * Implements hook_disable().
 *
 * the migration module should deregister its migrations
 */
function lw_teacher_migration_disable() {
  // based on: drupal.org/node/1418350#comment-5557772
  Migration::deregisterMigration('lw_Step1_Teacher');
  Migration::deregisterMigration('lw_Step2_Teacher');
  Migration::deregisterMigration('lw_TeacherTerm');
  Migration::deregisterMigration('lw_TeacherBranch');
}
?>